### ISSUE TITLE
Content details is not dynamic

### ISSUE THREAD

**Issue by t694575** [b5i/InfiniteScrollViews#1]
Hi and good day.
Tried to use the binding for updating value of my content (Is this possible?).
Also saw this warning 
<img width="1049" alt="Screenshot 2023-07-26 at 6 00 05 PM" src="https://github.com/b5i/InfiniteScrollViews/assets/105712972/1b628db6-0b4b-49bd-9025-1690009fce6e">

**Comment by b5i** [comment]
> Hi and good day.
> 
> Tried to use the binding for updating value of my content (Is this possible?).
> 
> Also saw this warning 
> 
> <img width="1049" alt="Screenshot 2023-07-26 at 6 00 05 PM" src="https://github.com/b5i/InfiniteScrollViews/assets/105712972/1b628db6-0b4b-49bd-9025-1690009fce6e">
> 
> 

Hello, thanks for trying InfiniteScrollViews! Currently, updateBinding exists to update the potential nil value at the edges of the ScrollView. When you talk about updating the content details, do you mean update the ScrollView with a kind of Binding of the changeIndex property?

**Comment by t694575** [comment]
> > Hi and good day.
> > Tried to use the binding for updating value of my content (Is this possible?).
> > Also saw this warning
> > <img alt="Screenshot 2023-07-26 at 6 00 05 PM" width="1049" src="https://user-images.githubusercontent.com/105712972/256194916-1b628db6-0b4b-49bd-9025-1690009fce6e.png">
> 
> Hello, thanks for trying InfiniteScrollViews! Currently, updateBinding exists to update the potential nil value at the edges of the ScrollView. When you talk about updating the content details, do you mean update the ScrollView with a kind of Binding of the changeIndex property?

thanks for the reply. 
I have this content where it has a list of text that changes every minute. eg. first view: "A" -> after a minute -> first view: "B". Any tips how to achieve it like this? thanks

**Comment by b5i** [comment]
> > > Hi and good day.
> > > Tried to use the binding for updating value of my content (Is this possible?).
> > > Also saw this warning
> > > <img alt="Screenshot 2023-07-26 at 6 00 05 PM" width="1049" src="https://user-images.githubusercontent.com/105712972/256194916-1b628db6-0b4b-49bd-9025-1690009fce6e.png">
> > 
> > 
> > Hello, thanks for trying InfiniteScrollViews! Currently, updateBinding exists to update the potential nil value at the edges of the ScrollView. When you talk about updating the content details, do you mean update the ScrollView with a kind of Binding of the changeIndex property?
> 
> thanks for the reply. I have this content where it has a list of text that changes every minute. eg. first view: "A" -> after a minute -> first view: "B". Any tips how to achieve it like this? thanks

I would personally use a kind of model or a [Timer](https://developer.apple.com/documentation/foundation/timer) to connect the views with time.
