### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by longvudai** [b5i/InfiniteScrollViews#3]
This package is truly amazing. Could you provide support for macOS? @b5i

**Comment by b5i** [comment]
> This package is truly amazing. 

Thank you!

> Could you provide support for macOS? @b5i 

Hello, indeed, it would be a great feature! I will try implement it.

**Comment by b5i** [comment]
I made a beginning of support for macOS in [`a98923b`](https://github.com/b5i/InfiniteScrollViews/commit/a98923b134d2c03a044a750f53371d39452ba938), let me know if it works well for you.

**Comment by longvudai** [comment]
@b5i Could you also implement PagedInfiniteScrollView? I'm really looking forward to it because I think it would be very useful

**Comment by b5i** [comment]
Of course! 
I'm also working on this and the horizontal mode should be added in a few days.

**Comment by b5i** [comment]
Support for `NSPagedInfiniteScrollView` should be working from [`1888ab2`](https://github.com/b5i/InfiniteScrollViews/commit/1888ab29dd6c7fc2a8db4d0bc138b37cbec2dc63), let me know if it works on your side.

**Comment by longvudai** [comment]
@b5i Works like a charm, bro! Nailed it.
