### ISSUE TITLE
MacOS PagedInfinite UI issue

### ISSUE THREAD

**Issue by vuthanhdo** [b5i/InfiniteScrollViews#4]
Dear b5i,

I hope you are doing well.

First, thank you for your wonderful library; I have been using it, and it works great!

However, I have encountered an issue when using the PagedInfiniteScrollView (used PagedCalendarView in your example project) on macOS. Specifically, the content view seems misaligned (shifted to the left and top) when the view is initialized for the first time. After scrolling through a few pages, the content view aligns correctly to the center.

Please help update or fix this issue.

I truly appreciate your support and assistance.

Best regards,
dovt

https://github.com/user-attachments/assets/bf7813e4-10b5-4887-8f26-8c84e13f6a96

**Comment by b5i** [comment]
Hello, thank you for pointing that problem. I'm going to check that on my side to see what I can do 🚀

**Comment by b5i** [comment]
Hello! I made my little investigation and found out that it was the same bug that caused the calendar view not to render properly in the example project. The issue should be resolved starting from [`adec1af`](https://github.com/b5i/InfiniteScrollViews/commit/adec1afc091e1f6e367da585a3cb699c2cb95a5f).
Let me know if you encounter any other issues!
